### ISSUE TITLE
srtm issue

### ISSUE THREAD

**Issue by tanmaygatle** [gfacciol/IS18#2]
under crop_aoi function there is the following code:

lon, lat  = aoi_buenos_aires['center']
z = srtm4.srtm4(lon, lat)

the values of lon, lat are -58.5841445, -34.4900515
z = srtm4.srtm4(lon,lat) returns error because 'alts' list is empty.
This is because when srtm4 executable is called with input = lon_lat, it returns nan.
 
Following is the code from srtm4.py  from which it returns nan - 

    p = subprocess.Popen(['%s/srtm4/srtm4'%here],
                         stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                         env={'PATH': BIN, 'SRTM4_CACHE': SRTM_DIR})
    outs, errs = p.communicate(input=lon_lats.encode())

I am running the code on Google Colab and I have made the executable "srtm4" by running 'make' in the srtm4 folder. 
![1](https://user-images.githubusercontent.com/22378228/55229933-55aa7900-5244-11e9-911e-a05d11f2e53a.png)

**Comment by carlodef** [comment]
Hi @tanmaygatle, you can fix this with

     pip install srtm4

**Comment by tanmaygatle** [comment]
After doing as suggested, I got the message that the requirement srtm4 was already satisfied..The error is the same yet.

**Comment by gfacciol** [comment]
That's because the srtm4.py file is still in your directory. Just rename it to  srtm4_.py (or delete)  and do the same with the directory srtm4. I've updated the Docker, the requirements.txt, and renamed the files in a fix.

As a side note, some widgets used in the notebook might not work on colab.
