### ISSUE TITLE
DEM values not matching groundtruth

### ISSUE THREAD

**Issue by daviddemeij** [gfacciol/IS18#3]
I have been running through your notebook, which has been very useful for us.  However, we encounter a problem with the output values, the values are realistic (building height compared to the surface seems to be correct), but the surface height doesn't match with our SRTM.

The same problem seems to occur when I run through the notebook using the example, since the values of the output DEM don't match the SRTM height either and also don't match the ground truth values found [here](https://gfacciol.github.io/multi-date-stereo/).
![output_dem](https://user-images.githubusercontent.com/19728972/59416920-971fde80-8dc6-11e9-8f2b-2725dddaa517.png)

I have considered adding the SRTM value (25.13) to the DEM, but then the values are too high.

Do you have any idea what the issue is? And how we can get the DEM on the same scale or use the same basis as the SRTM?

**Comment by carlodef** [comment]
Hi @daviddemeij, the issue is probably that SRTM heights are with respect to the EGM96 geoid while our DEM heights are with respect to the WGS84 ellipsoid. You need to account for the geoid - ellipsoid offset when comparing.

**Comment by daviddemeij** [comment]
Thank you very much for the response, this is very helpful. 

So if I understand it correctly, using the tool we calculate the `GPS ellipsoidal height` and the SRTM contains the `orthometric height` which is the ellipsoidal height corrected by using the `geoid height`?

`orthometric height = GPS ellipsoidal height - geoid height)`
