### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by makaay2077** [gfacciol/IS18#8]
Hello. Your work is very good, I congratulate you. However, when I run it on Ubuntu and Colab, I get errors. In Exercise 2, this code section gives an error from its output.

Exercise 2

idx_a=37
idx_b=38
aoi = aoi_buenos_aires

rect1, rect2, S1, S2, dmin, dmax, PA, PB = rectification.rectify_aoi(myimages[idx_a], 
                                                                     myimages[idx_b], 
                                                                     aoi)

dmin, dmax = dmin-20, dmax+20

if False:  
    dmin, dmax = -60,0
    rect1=utils.readGTIFF('data/im2.png')
    rect2=utils.readGTIFF('data/im6.png')

 
print('Disparity range: [%d, %d]'%(dmin,dmax))
lambdaval=10
LRSsd, dLsd, _ =  stereo.compute_disparity_map(rect1,rect2,dmin,dmax,cost='sd',  lam=lambdaval*10)
LRS  , dL  , _ =  stereo.compute_disparity_map(rect1,rect2,dmin,dmax,cost='census', lam=lambdaval)

print('Comparison with sd cost and results without filtering results')
vistools.display_gallery([utils.simple_equalization_8bit(LRS),
                          utils.simple_equalization_8bit(LRSsd),
                          utils.simple_equalization_8bit(dL),
                          utils.simple_equalization_8bit(dLsd),
                          utils.simple_equalization_8bit(rect1),
                          utils.simple_equalization_8bit(rect2)
                         ], 
                         ['census filtered', 'sd filtered','census', 
                          'sd','ref','sec'])

vistools.display_imshow(LRS, cmap='jet')

Output:

[ WARN:0] global /tmp/pip-req-build-hj027r8z/opencv_contrib/modules/xfeatures2d/misc/python/shadow_sift.hpp (13) SIFT_create DEPRECATED: cv.xfeatures2d.SIFT_create() is deprecated due SIFT tranfer to the main repository. https://github.com/opencv/opencv/issues/16736

Disparity range: [-22, 24]
t=0.2886 done building CV

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_11891/1422833750.py in <module>
     22 print('Disparity range: [%d, %d]'%(dmin,dmax))
     23 lambdaval=10
---> 24 LRSsd, dLsd, _ =  stereo.compute_disparity_map(rect1,rect2,dmin,dmax,cost='sd',  lam=lambdaval*10)
     25 LRS  , dL  , _ =  stereo.compute_disparity_map(rect1,rect2,dmin,dmax,cost='census', lam=lambdaval)
     26 

~/Desktop/work/stereo.py in compute_disparity_map(rect1, rect2, dmin, dmax, cost, lam)
    587 
    588     # compute left and right disparity maps
--> 589     dL =  stereoSGM(im1,im2,dmin,dmax,lam=lam,cost=cost, cw=cw, win=win, subpix_refine=subpix_refine)
    590     dR =  stereoSGM(im2,im1,-dmax,-dmin,lam=lam,cost=cost, cw=cw, win=win, subpix_refine=subpix_refine)
    591 

~/Desktop/work/stereo.py in stereoSGM(im1, im2, dmin, dmax, lam, cost, cw, win, subpix_refine)
    541 
    542     print ('t={:2.4f} done building CV'.format(time.time() - start_time))
--> 543     CV = sgmfilter(CV,lam)         # SGM
    544 
    545     print ('t={:2.4f} done sgmfilter'.format(time.time() - start_time))

~/Desktop/work/stereo.py in sgmfilter(CV, lam)
    430 
    431     for i in range(CV.shape[0]):
--> 432         fw = viterbiV(CV[i,:,:],lam)
    433         bw = viterbiV(CV[i,::-1,:],lam)
    434         S[i,:,:] += fw + bw[::-1]

TypeError: expected dtype object, got 'numpy.dtype[float64]'

I hope you can help.Thanks

**Comment by gfacciol** [comment]
Thanks! I've updated the requirements in the colab notebook. Now it works!
